//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IslandM.Spec
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageSpecEntity
    {
        public int StageID { get; set; }
        public string Name { get; set; }
        public sbyte StageType { get; set; }
        public sbyte Level { get; set; }
        public int NextStageID { get; set; }
        public sbyte NeedEnergy { get; set; }
        public sbyte PhaseCount { get; set; }
        public int BossID { get; set; }
        public short AccountExp { get; set; }
        public short HeroExp { get; set; }
        public short GainGoldMax { get; set; }
        public short GainGoldMin { get; set; }
        public int ClearRewardID { get; set; }
        public short LimitTime { get; set; }
        public short GainStarTime { get; set; }
        public bool RemoveStarWhenDied { get; set; }
    }
}
