services:
  mysql:
    image: mysql:8
    container_name: sk-backend-mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "sk1234!"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_0900_ai_ci"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-psk1234!"]
      interval: 3s
      timeout: 5s
      retries: 30

  redis:
    image: redis:7
    container_name: sk-backend-redis
    ports:
      - "16379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 20
