CREATE TABLE IF NOT EXISTS tbl_station (
  AccountIdx BIGINT NOT NULL PRIMARY KEY,
  Food BIGINT NOT NULL DEFAULT 0,
  Parts BIGINT NOT NULL DEFAULT 0,
  Energy BIGINT NOT NULL DEFAULT 0,
  Vouchers BIGINT NOT NULL DEFAULT 0,
  LastUpdated DATETIME NOT NULL,
  SupplyLevel INT NOT NULL DEFAULT 1,
  WorkshopLevel INT NOT NULL DEFAULT 1,
  SubstationLevel INT NOT NULL DEFAULT 1,
  ExchangeLevel INT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS tbl_station_construction (
  AccountIdx BIGINT NOT NULL PRIMARY KEY,
  FacilityKind INT NOT NULL,
  TargetLevel INT NOT NULL,
  StartedAt DATETIME NOT NULL,
  CompletesAt DATETIME NOT NULL
);
