export const wikiLinks = {
  home: '/',
  states: '/states',
  documents: '/documents',
  categories: '/categories',
  worldIndex: '/world/',
  overview: '/world/World-Unbinding',
  timeline: '/world/Scenario-Timeline',
  offices: '/world/Offices-and-Ranks',
  houses: '/world/Chaebol-Houses-and-Century-Factions',
  characters: '/people',
  castIndex: '/people',
  hangnyeol: '/world/Hangnyeol-and-Bon-gwan',
  operatingHouses: '/world/Operating-Houses',
  faith: '/world/Faith-Culture-Schism',
  technology: '/world/Era-Arms-and-Tech-Level',
  food: '/world/Food-Culture',
  structures: '/world/Structures',
  subway: '/world/World-and-Subway-Layers',
  stations: '/world/Seoul-Station-Catalog',
  regions: '/world/World-and-Subway-Layers',
  peopleAndMachines: '/world/People-and-Machines',
  ailments: '/world/Ailments',
} as const
