import * as game from './model.mjs';

const world=window.POC_WORLD;
const $=(id)=>document.getElementById(id);
const state={game:game.createGame(24601),started:false,selectedUnit:'guard',mapKey:'',listKey:'',lastLog:''};
const regionById=new Map(world.regions.map(r=>[r.id,r]));
const regionNodes=new Map();
const phaseLabel={home:' 거점',planning:'원정 준비',encounter:'조우',deployment:'진형 배치',battle:'전투 중',result:'결과 확인',settled:'정산 완료'};
const roleLabel={guard:'방어',assault:'돌격',ranger:'지원',archer:'원거리'};
const roleSymbol={guard:'▣',assault:'╱',ranger:'⊕',archer:'⌁'};
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function btn(id,text,fn,cls='primary'){const b=el('button',text,cls);b.type='button';b.id=id;b.addEventListener('click',fn);return b;}
function action(fn){try{const next=fn(state.game);if(next)state.game=next;$('error').hidden=true;render();}catch(error){$('error').textContent=error.message;$('error').hidden=false;}}
function sign(n){return `${n>0?'+':''}${n}`;}
function distance(region){return Math.hypot(region.centroid[0]-world.home.centroid[0],region.centroid[1]-world.home.centroid[1])/1000;}
function destination(){return regionById.get(state.game.destination?.id)??state.game.destination;}
function setDestination(id){if(!state.started){state.started=true;state.game=game.beginPlanning(state.game);}else if(state.game.phase==='home'){state.game=game.beginPlanning(state.game);}if(state.game.phase!=='planning'){showMessage('목적지는 거점에서 다음 원정을 준비할 때 바꿀 수 있습니다.');return;}action(s=>game.selectDestination(s,regionById.get(id)));}
function showMessage(message){$('error').textContent=message;$('error').hidden=false;}

const allPoints=world.regions.flatMap(r=>r.geometry.type==='Polygon'?r.geometry.coordinates.flat():r.geometry.coordinates.flat(2));
let xmin=Infinity,ymin=Infinity,xmax=-Infinity,ymax=-Infinity;
for(const [x,y] of allPoints){xmin=Math.min(xmin,x);xmax=Math.max(xmax,x);ymin=Math.min(ymin,y);ymax=Math.max(ymax,y);}
const scale=Math.min(670/(xmax-xmin),500/(ymax-ymin));
const project=([x,y])=>[(x-xmin)*scale+(760-(xmax-xmin)*scale)/2,(ymax-y)*scale+50];
const svgNS='http://www.w3.org/2000/svg';
for(const r of world.regions){const node=document.createElementNS(svgNS,'path');const polygons=r.geometry.type==='Polygon'?[r.geometry.coordinates]:r.geometry.coordinates;const d=[];for(const poly of polygons)for(const ring of poly)d.push(ring.map((p,i)=>{const [x,y]=project(p);return`${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`;}).join(' ')+'Z');node.setAttribute('d',d.join(' '));node.setAttribute('fill-rule','evenodd');node.setAttribute('class','district-shape');node.dataset.regionId=r.id;const title=document.createElementNS(svgNS,'title');title.textContent=`${r.district} ${r.name}`;node.append(title);node.addEventListener('click',()=>setDestination(r.id));$('world-map').append(node);regionNodes.set(r.id,node);}
const routeLine=document.createElementNS(svgNS,'line');routeLine.setAttribute('stroke','#efaa67');routeLine.setAttribute('stroke-width','2');routeLine.setAttribute('stroke-dasharray','5 7');routeLine.setAttribute('pointer-events','none');$('world-map').append(routeLine);
for(const district of world.districts){const parts=world.regions.filter(r=>r.district===district);const centroid=parts.reduce((a,r)=>[a[0]+r.centroid[0]/parts.length,a[1]+r.centroid[1]/parts.length],[0,0]);const [x,y]=project(centroid);const text=document.createElementNS(svgNS,'text');text.setAttribute('x',x);text.setAttribute('y',y);text.setAttribute('text-anchor','middle');text.setAttribute('class','map-label');text.textContent=district.replace('구','');$('world-map').append(text);const opt=el('option',district);opt.value=district;$('district-filter').append(opt);}
const marker=document.createElementNS(svgNS,'g');const homePoint=project(world.home.centroid);const dot=document.createElementNS(svgNS,'circle');dot.setAttribute('cx',homePoint[0]);dot.setAttribute('cy',homePoint[1]);dot.setAttribute('r','5');dot.setAttribute('fill','#c4dcab');dot.setAttribute('stroke','#15252c');dot.setAttribute('stroke-width','2');marker.append(dot);const homeLabel=document.createElementNS(svgNS,'text');homeLabel.setAttribute('x',homePoint[0]+9);homeLabel.setAttribute('y',homePoint[1]+18);homeLabel.setAttribute('class','map-point-label');homeLabel.textContent='영등포 거점';marker.append(homeLabel);$('world-map').append(marker);

function drawMap(){const gu=$('district-filter').value,q=$('region-search').value.trim();const key=[gu,q,state.game.destination?.id,state.game.phase].join('|');if(key===state.mapKey)return;state.mapKey=key;
const filtered=world.regions.filter(r=>(!gu||r.district===gu)&&(!q||`${r.district} ${r.name}`.includes(q)));const ids=new Set(filtered.map(r=>r.id));for(const [id,p]of regionNodes){p.classList.toggle('dim',!ids.has(id));p.classList.toggle('selected',id===state.game.destination?.id);p.classList.toggle('home',id===world.home.id);}
const selected=destination();routeLine.style.display=selected?'':'none';if(selected){const target=project(selected.centroid);routeLine.setAttribute('x1',homePoint[0]);routeLine.setAttribute('y1',homePoint[1]);routeLine.setAttribute('x2',target[0]);routeLine.setAttribute('y2',target[1]);}
const list=$('region-list');list.replaceChildren();const sorted=[...filtered].sort((a,b)=>distance(a)-distance(b));$('region-count').textContent=`${filtered.length}개 동`;$('destinations-title').textContent=gu||q?'검색한 지역':'가까운 곳부터 시작해 보세요';
for(const r of sorted){const b=el('button',undefined,'region-option');b.type='button';b.dataset.regionId=r.id;b.setAttribute('aria-pressed',String(r.id===state.game.destination?.id));b.append(el('strong',r.name),el('small',`${r.district} · 위험 ${'●'.repeat(r.risk)} · ${distance(r).toFixed(1)}km`));b.addEventListener('click',()=>setDestination(r.id));list.append(b);}if(!filtered.length)list.append(el('p','검색한 지역이 없습니다. 동 이름이나 구 필터를 바꿔보세요.','empty'));
$('map-hint').textContent=selected?`${selected.district} ${selected.name} · ${selected.theme} 문제 · 위험 ${selected.risk}/3`:'지역을 눌러 비용과 위험을 확인하세요.';}

function resources(){const g=state.game;const hp=g.squad.reduce((a,u)=>a+u.hp,0),max=g.squad.reduce((a,u)=>a+u.maxHp,0);$('resources').replaceChildren();for(const [icon,label,value]of[['◇','물자',g.supplies],['⌘','평판',g.reputation],['↗','완료 원정',g.expeditions],['＋','분대 체력',`${hp}/${max}`]]){const r=el('div',undefined,'resource');const text=el('span');text.append(el('small',label),el('b',String(value)));r.append(el('i',icon),text);$('resources').append(r);}
$('flow').replaceChildren();const active=['home','planning'].includes(g.phase)?0:['encounter','deployment','battle'].includes(g.phase)?1:2;for(const [i,title]of ['거점에서 준비','원정과 선택','정산하고 귀환'].entries()){const n=el('div',undefined,'flow-step'+(i===active?' active':''));n.append(el('b',String(i+1).padStart(2,'0')),el('span',title));$('flow').append(n);}document.body.dataset.phase=g.phase;}
function price(items){const p=el('div',undefined,'price');for(const [label,value]of items){const s=el('span',label);s.append(el('b',value));p.append(s);}return p;}
function renderSituation(){const g=state.game,p=$('situation'),r=destination();p.replaceChildren();p.append(el('p',`${String(g.day).padStart(2,'0')}일차 / ${phaseLabel[g.phase]}`,'eyebrow'));
if(g.phase==='home'){p.append(el('h2',g.expeditions?'돌아왔습니다.':'영등포의 아침'),el('p',g.expeditions?'지난 선택의 결과가 분대에 남아 있습니다. 체력을 회복하고 다음 원정을 계획하세요.':'적은 물자로 시작합니다. 멀리 가면 비용이 늘고, 싸우면 분대가 다칠 수 있습니다. 한 번 나가서 돌아와 보세요.'));p.append(price([['분대 인원',`${g.squad.filter(u=>u.hp>0).length} / 3`],['보유 물자',String(g.supplies)]]));p.append(btn('begin-planning','다음 원정 준비 →',()=>{state.started=true;action(game.beginPlanning);}));p.append(btn('rest','거점에서 분대 회복',()=>action(game.rest),'secondary'));p.append(el('p','원정은 물자를 쓰고 결과는 한 번 정산됩니다. 패배해도 거점에서 다시 시작할 수 있습니다.','hint'));}
else if(g.phase==='planning'){p.append(el('h2',r?r.name+'으로':'어디로 갈까요?'),el('p',r?`${r.district} · ${r.theme} 갈등이 기다립니다.`:'지도나 아래 목록에서 목적지를 고르세요. 비용과 위험을 확인한 뒤 출발할 수 있습니다.'));if(r){p.append(el('div',`현지 장소 · ${r.anchorName}`,'context-place'));p.append(el('p',r.summary));p.append(price([['이동 물자',`−${game.departureCost(g)}`],['예상 위험',`${r.risk} / 3`]]));p.append(btn('depart','물자를 챙겨 출발 →',()=>action(game.depart)));p.append(el('p','거리에서 유도한 체험용 비용입니다. 점선은 실제 철도·보행 경로가 아닙니다.','hint'));}else p.append(el('p','가까운 곳은 비용을 아낄 수 있습니다. 목적지를 고르면 예상 비용이 여기 나타납니다.','hint'));}
else if(g.phase==='encounter'){p.append(el('h2',`${r.name}, 길이 막혔다`),el('div',`현지 장소 · ${r.anchorName}`,'context-place'),el('p',`원정대는 ${r.theme} 문제를 놓고 현지 공동체와 마주했습니다. 대화로 풀거나, 손해를 감수하고 우회하거나, 길을 막은 적과 싸울 수 있습니다.`));const chance=Math.round(game.negotiationChance(g)*100);for(const [id,title,hint,fn]of [['negotiate','협상한다',`물자 5 · 성공 가능성 ${chance}% · 성공하면 평판 상승`,game.negotiate],['bypass','우회한다','물자를 더 쓰고 충돌 없이 지나갑니다. 평판에는 불리합니다.',game.bypass],['choose-combat','전투로 해결한다','진형을 정하고 소유 카드로 개입합니다. 부상 위험이 있습니다.',game.prepareBattle]]){const b=btn(id,undefined,()=>action(fn),'choice-card');b.append(el('strong',title),el('small',hint));p.append(b);}p.append(el('p','무엇을 얻고 잃는지 결과 화면에서 비교할 수 있습니다.','hint'));}
else if(g.phase==='deployment'){p.append(el('h2','전열을 정하세요'),el('p','방어 역할은 앞에, 지원 역할은 뒤에 두면 오래 버팁니다. 유닛을 고른 뒤 진형 칸을 눌러 배치를 바꾸세요.'),price([['분대',`${g.squad.filter(u=>u.hp>0).length}명`],['현지 위험',`${r.risk} / 3`]]),el('p','칸을 바꾸면 기존 유닛과 자리를 맞바꿉니다. 전투 시작 뒤에는 병사가 자동으로 움직입니다.','hint'));}
else if(g.phase==='battle'){const b=g.battle;p.append(el('h2',b.paused?'멈추고, 판단하세요.':'분대가 싸우고 있습니다.'),el('p','개별 병사를 움직이지 않습니다. 방어·공격·회복 카드를 적절한 순간에 사용하세요. 카드 주인이 쓰러지면 그 카드는 사용할 수 없습니다.'),price([['지휘 에너지',String(Math.floor(b.energy))],['남은 적',String(b.enemies.filter(u=>u.hp>0).length)]]),el('p','일시정지 중에는 병사 이동과 재충전이 멈춥니다. 카드의 효과는 분대의 생존과 승패에 영향을 줍니다.','hint'));}
else if(g.phase==='result'||g.phase==='settled'){const res=g.result;p.append(el('h2',res.title),el('p',res.description));const del=el('div',undefined,'delta-row');for(const [label,n]of [['물자',res.suppliesDelta],['평판',res.reputationDelta]]){const x=el('div',undefined,'delta'+(n<0?' bad':''));x.append(el('small',label),el('strong',sign(n)));del.append(x);}p.append(del);if(g.phase==='result'){p.append(btn('settle','결과를 정산한다 →',()=>action(game.settle)),el('p','정산을 눌러야 물자와 평판이 반영됩니다. 같은 결과는 두 번 받을 수 없습니다.','hint'));}else{p.append(btn('return-home','영등포 거점으로 돌아간다 →',()=>action(game.returnHome)),el('p','정산 완료. 부상과 남은 물자는 다음 원정으로 이어집니다.','hint'));}}
}
function squadAndLog(){const g=state.game;$('squad').replaceChildren();for(const u of g.squad){const row=el('div',undefined,'squad-unit');row.append(el('span',roleSymbol[u.role]??'◇','unit-emblem'));const body=el('div',undefined,'unit-body'),name=el('strong',u.name);name.append(el('small',roleLabel[u.role]??u.role));body.append(name);const track=el('div',undefined,'hp-track'),fill=el('i');fill.style.width=`${Math.max(0,u.hp/u.maxHp)*100}%`;track.append(fill);body.append(track);row.append(body,el('span',`${Math.max(0,Math.ceil(u.hp))}/${u.maxHp}`,'hp-number'));$('squad').append(row);}const key=g.log.map(l=>l.id).join('|');if(key!==state.lastLog){state.lastLog=key;$('event-log').replaceChildren();for(const event of g.log.slice(-12).reverse())$('event-log').append(el('li',event.text,event.kind));$('log-count').textContent=`${g.log.length}건`;}}

function formationAndCards(){const g=state.game;$('formation-editor').hidden=g.phase!=='deployment';$('cards').hidden=g.phase!=='battle';$('battle-controls').replaceChildren();if(g.phase==='deployment'){const box=$('formation-editor');box.replaceChildren();const info=el('div',undefined,'formation-info');info.append(el('strong','유닛을 고른 뒤 칸을 누르세요'));const select=el('select');select.id='formation-unit';select.setAttribute('aria-label','진형을 바꿀 유닛');for(const u of g.squad){const o=el('option',`${u.name} · ${roleLabel[u.role]??u.role}`);o.value=u.id;select.append(o);}if(!g.squad.some(u=>u.id===state.selectedUnit))state.selectedUnit=g.squad[0].id;select.value=state.selectedUnit;select.addEventListener('change',()=>{state.selectedUnit=select.value;formationAndCards();});info.append(select,el('span','위쪽: 전열 / 아래쪽: 후열'));const grid=el('div',undefined,'formation-grid');for(let slot=0;slot<9;slot++){const unit=g.squad.find(u=>u.slot===slot);const b=el('button',unit?(roleSymbol[unit.role]??'◇'):'·');b.type='button';b.dataset.slot=slot;b.classList.toggle('selected',unit?.id===state.selectedUnit);b.setAttribute('aria-label',`${slot+1}번 칸 ${unit?unit.name:'빈 자리'}`);b.addEventListener('click',()=>action(s=>game.setFormation(s,state.selectedUnit,slot)));grid.append(b);}box.append(info,grid);$('battle-controls').append(btn('begin-battle','이 진형으로 전투 시작 →',()=>action(game.startBattle)));}
else if(g.phase==='battle'){$('battle-controls').append(btn('pause-battle',g.battle.paused?'전투 계속 ▶':'일시정지 Ⅱ',()=>action(game.togglePause),'secondary'),btn('retreat','손실을 감수하고 후퇴',()=>action(game.retreat),'danger'));}
$('cards').replaceChildren();if(g.phase==='battle')for(const card of game.CARDS){const b=el('button',undefined,'command-card');b.type='button';b.dataset.card=card.id;const owner=g.battle.allies.find(u=>u.id===card.ownerId);const remaining=Math.max(0,(g.battle.cooldowns[card.id]??0)-g.battle.tick);const justMoved = g.battle.events.some(entry => entry.kind === 'move' && entry.tick === g.battle.tick && entry.unitId === card.ownerId);
const ready = owner?.hp > 0 && remaining === 0 && g.battle.energy >= card.cost && !justMoved;const top=el('div',undefined,'card-top');top.append(el('span',owner?.name??'소유 카드'),el('b',`◇ ${card.cost}`));b.append(top,el('span',card.kind==='heal'?'＋':card.kind==='shield'?'▣':'╱','card-icon'),el('strong',card.title),el('small',card.description),el('span', owner?.hp <= 0 ? '소유자 전투 불능' : remaining ? `${(remaining / 30).toFixed(1)}초 후 재사용` : g.battle.energy < card.cost ? '에너지 부족' : justMoved ? '이동 직후 — 잠깐 대기' : '사용 가능', 'card-status'));b.disabled=!ready;b.addEventListener('click',()=>action(s=>game.playCard(s,card.id)));$('cards').append(b);}}

const arena=$('arena'),ctx=arena.getContext('2d');
function iso(x,y){return[420+(x-y)*43,88+(x+y)*23];}
function drawArena(){const g=state.game;ctx.clearRect(0,0,1200,750);ctx.fillStyle='#10212a';ctx.fillRect(0,0,1200,750);for(let x=0;x<12;x++)for(let y=0;y<8;y++){const [sx,sy]=iso(x,y);ctx.beginPath();ctx.moveTo(sx,sy-22);ctx.lineTo(sx+42,sy);ctx.lineTo(sx,sy+22);ctx.lineTo(sx-42,sy);ctx.closePath();ctx.fillStyle=x<3?'#27453f':x>8?'#432f32':((x+y)%2?'#273941':'#2b3e46');ctx.fill();ctx.strokeStyle='#58707755';ctx.lineWidth=1;ctx.stroke();}
ctx.font='600 18px system-ui';ctx.fillStyle='#a9c8b0';ctx.fillText('우리 분대',96,325);ctx.fillStyle='#db9b90';ctx.fillText('적 진영',785,305);let units=[];if(g.battle){units=[...g.battle.allies,...g.battle.enemies];}else units=g.squad.map(u=>({...u,side:'ally',x:Math.floor(u.slot/3),y:2+u.slot%3}));
for(const u of [...units].sort((a,b)=>a.x+a.y-b.x-b.y)){const [x,y]=iso(u.x,u.y);const alive=u.hp>0;ctx.globalAlpha=alive?1:.25;ctx.fillStyle='#050b0e88';ctx.beginPath();ctx.ellipse(x,y+7,18,9,0,0,Math.PI*2);ctx.fill();const color=u.side==='ally'?'#c4dcab':'#e49485';ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x-13,y-8);ctx.lineTo(x-10,y-35);ctx.lineTo(x+10,y-35);ctx.lineTo(x+13,y-8);ctx.closePath();ctx.fill();ctx.fillStyle=u.side==='ally'?'#e9ead7':'#f2cbb6';ctx.beginPath();ctx.arc(x,y-43,9,0,Math.PI*2);ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x-6,y-8);ctx.lineTo(x-8,y+4);ctx.moveTo(x+6,y-8);ctx.lineTo(x+8,y+4);ctx.stroke();if(u.shield>0){ctx.strokeStyle='#89c8d8';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,y-24,24,31,0,0,Math.PI*2);ctx.stroke();}ctx.font='600 12px system-ui';ctx.textAlign='center';ctx.fillStyle='#edf0e8';ctx.fillText(u.name,x,y-65);ctx.fillStyle='#091319';ctx.fillRect(x-24,y-59,48,5);ctx.fillStyle=color;ctx.fillRect(x-24,y-59,48*Math.max(0,u.hp/u.maxHp),5);ctx.globalAlpha=1;}
ctx.textAlign='left';$('battle-clock').textContent=g.battle?`${String(Math.floor(g.battle.tick/30/60)).padStart(2,'0')}:${String(Math.floor(g.battle.tick/30)%60).padStart(2,'0')}`:'배치 중';$('battle-energy').textContent=g.battle?`지휘 에너지 ◇ ${Math.floor(g.battle.energy)}`:'';$('arena-message').textContent=g.phase==='deployment'?'진형의 전열과 후열을 바꿔 보세요.':g.battle?.paused?'일시정지 · 판단할 시간입니다.':g.phase==='result'||g.phase==='settled'?g.result.title:'실시간 전투 · 병사는 자동으로 움직입니다.';}

function render(){const g=state.game;$('intro').hidden=state.started;const showBattle=['deployment','battle'].includes(g.phase)||(['result','settled'].includes(g.phase)&&g.battle);$('world-panel').hidden=showBattle;$('battle-panel').hidden=!showBattle;resources();renderSituation();squadAndLog();drawMap();formationAndCards();if(showBattle)drawArena();}
$('start-game').addEventListener('click',()=>{state.started=true;action(game.beginPlanning);});$('reset-game').addEventListener('click',()=>{state.game=game.createGame(24601);state.started=false;state.mapKey='';state.lastLog='';$('district-filter').value='';$('region-search').value='';$('error').hidden=true;render();window.scrollTo({top:0,behavior:'auto'});});$('rules').addEventListener('click',()=>$('rules-dialog').showModal());$('district-filter').addEventListener('change',drawMap);$('region-search').addEventListener('input',drawMap);$('clear-search').addEventListener('click',()=>{$('district-filter').value='';$('region-search').value='';state.mapKey='';drawMap();});
let previous=0,accumulator=0,paintTick=0;function frame(now){if(!previous)previous=now;const elapsed=Math.min(150,now-previous);previous=now;if(state.game.phase==='battle'&&!state.game.battle.paused){accumulator+=elapsed;let steps=0;while(accumulator>=1000/game.TICKS_PER_SECOND&&steps<4&&state.game.phase==='battle'){state.game=game.stepGame(state.game,1);accumulator-=1000/game.TICKS_PER_SECOND;steps++;}if(state.game.phase!=='battle'||state.game.battle.tick-paintTick>=3){paintTick=state.game.battle?.tick??0;render();}}else accumulator=0;requestAnimationFrame(frame);}document.addEventListener('visibilitychange',()=>{previous=0;accumulator=0;});render();requestAnimationFrame(frame);
